//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelTakip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonelDBEntities : DbContext
    {
        public PersonelDBEntities()
            : base("name=PersonelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Cihaz> Tbl_Cihaz { get; set; }
        public virtual DbSet<Tbl_Drone> Tbl_Drone { get; set; }
        public virtual DbSet<Tbl_Faaliyet> Tbl_Faaliyet { get; set; }
        public virtual DbSet<Tbl_IhaTuru> Tbl_IhaTuru { get; set; }
        public virtual DbSet<Tbl_Personel> Tbl_Personel { get; set; }
        public virtual DbSet<Tbl_PersonelKurs> Tbl_PersonelKurs { get; set; }
        public virtual DbSet<Tbl_UcusKayit> Tbl_UcusKayit { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
    }
}
