//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personel
    {
        public int ID { get; set; }
        public string PerAd { get; set; }
        public string PerSoyad { get; set; }
        public string PerSicil { get; set; }
        public string PerRutbe { get; set; }
        public Nullable<int> PerSehirID { get; set; }
        public Nullable<int> PerKursID { get; set; }

        public virtual iller iller { get; set; }
        public virtual Tbl_IhaTuru Tbl_IhaTuru { get; set; }
        public virtual Tbl_PersonelKurs Tbl_PersonelKurs { get; set; }
        
    }
}
