//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UcusKayit
    {
        public int UcusKayitID { get; set; }
        public Nullable<int> DroneID { get; set; }
        public Nullable<int> FaaliyetID { get; set; }
        public Nullable<System.DateTime> UcusTarihi { get; set; }
        public Nullable<System.TimeSpan> UcusSuresi { get; set; }
    
        public virtual Tbl_Drone Tbl_Drone { get; set; }
        public virtual Tbl_Faaliyet Tbl_Faaliyet { get; set; }
    }
}
