//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Drone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Drone()
        {
            this.Tbl_UcusKayit = new HashSet<Tbl_UcusKayit>();
        }
    
        public int DroneID { get; set; }
        public Nullable<int> DroneAdID { get; set; }
        public string DroneSeriNo { get; set; }
        public string DroneNot { get; set; }
        public Nullable<int> SehirID { get; set; }
        public Nullable<int> DroneTuruID { get; set; }
    
        public virtual iller iller { get; set; }
        public virtual Tbl_Cihaz Tbl_Cihaz { get; set; }
        public virtual Tbl_IhaTuru Tbl_IhaTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UcusKayit> Tbl_UcusKayit { get; set; }
    }
}
